#logging.level.root: DEBUG
#logging.level.org.springframework.web: DEBUG
logging.level.org.springframework.ws: TRACE
spring:
  profiles:
    active:
    - dev
  jackson:
    time-zone: Europe/Madrid
  datasource:
    url: jdbc:h2:mem:TIAADM;MVCC=true;DB_CLOSE_DELAY=-1;MODE=MYSQL;DB_CLOSE_ON_EXIT=TRUE
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
    platform: h2
    initialize: true
    test-while-idle: true
    test-on-borrow: false
    validationQuery: SELECT 1
  jpa.show-sql: true
  jpa.hibernate.dialect: org.hibernate.dialect.MySQLDialect
  jpa.properties.hibernate.format_sql: true
  jpa.properties.hibernate.type: trace
  #jpa.hibernate.ddl-auto: none
  h2.console.enabled: true
  h2.console.path: /h2
security.basic.enabled: false
    user:
      name: tjoelsm
      password: sapo
  whiteList:
    - /admin/health
    - /**
management:
  context-path: /admin
  security:
    enabled: false