#logging.level.root: DEBUG
#logging.level.org.springframework.web: DEBUG
logging.level.org.springframework.ws: TRACE
spring:
  jackson:
    time-zone: Europe/Madrid
  datasource:
    url: jdbc:mysql://mysql:3306/exesDB?useSSL=false
    username: "root"
    password: "tiago123"
    driver-class-name: com.mysql.cj.jdbc.Driver
    test-while-idle: true
    test-on-borrow: false
    validationQuery: SELECT 1
  jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
  jpa.show-sql: true
  jpa.hibernate.dialect: org.hibernate.dialect.MySQLDialect
  jpa.properties.hibernate.format_sql: true
  jpa.properties.hibernate.type: trace
  #jpa.properties.hibernate.default_schema: exesDB
  jpa.hibernate.ddl-auto: none
  whiteList:
    - /admin/health
    - /**
management.security.enabled: false
security.basic.enabled: false