DROP TABLE IF EXISTS TIA_SEG_PERSONAS;
CREATE TABLE IF NOT EXISTS TIA_SEG_PERSONAS (
  TIA01_COD_PERSONA INT NOT NULL AUTO_INCREMENT,
  TIA01_NOMBRE VARCHAR(200) NULL,
  TIA01_APELLIDOS VARCHAR(200) NULL,
  TIA01_DIRELEC VARCHAR(200) NOT NULL,
  TIA01_ULTIMO_ACCESS DATETIME NULL,
  TIA01_LOGIN_PASS VARCHAR(10) NULL,
  PRIMARY KEY (TIA01_COD_PERSONA, TIA01_DIRELEC)
 );
INSERT INTO TIA_SEG_PERFIL VALUES('Tiago Joel', 'Da Silva Monteiro', 'tjoelsm@gmail.com', CURRENT_DATE, 'tiago123');

