DROP TABLE IF EXISTS TIA_SEG_PERSONAS;
CREATE TABLE IF NOT EXISTS TIA_SEG_PERSONAS (
  TIA01_COD_PERSONA INT NOT NULL AUTO_INCREMENT,
  TIA01_NOMBRE VARCHAR(200) NULL,
  TIA01_APELLIDOS VARCHAR(200) NULL,
  TIA01_DIRELEC VARCHAR(200) NOT NULL,
  TIA01_ULTIMO_ACCESS DATETIME NULL,
  TIA01_LOGIN_PASS VARCHAR(10) NULL,
  PRIMARY KEY (TIA01_COD_PERSONA, TIA01_DIRELEC)
 );
INSERT INTO TIA_SEG_PERFIL VALUES('Tiago Joel', 'Da Silva Monteiro', 'tjoelsm@gmail.com', CURRENT_DATE, 'tiago123');
-- -----------------------------------------------------
-- Table TIA_APP_GASTOS_GRUPO
-- -----------------------------------------------------
DROP TABLE IF EXISTS TIA_APP_GASTOS_GRUPO;
CREATE TABLE IF NOT EXISTS TIA_APP_GASTOS_GRUPO (
  TAP04_COD_GRUPO VARCHAR(6) NOT NULL,
  TAP_COD_TIPOGASTO VARCHAR(3) NOT NULL,
  TAP04_NOMBRE_GRUPO VARCHAR(45) NULL,
  PRIMARY KEY (TAP04_COD_GRUPO, TAP_COD_TIPOGASTO)
);
-- -----------------------------------------------------
-- Table TIA_APP_INGRESOS
-- -----------------------------------------------------
DROP TABLE IF EXISTS TIA_APP_INGRESOS;

CREATE TABLE IF NOT EXISTS TIA_APP_INGRESOS (
  TAP05_COD_TIPOINGRESO VARCHAR(3) NOT NULL,
  TAP05_DEC_INGRESO VARCHAR(45) NULL,
  TAP05_PRIOCIDAD INT NULL,
  TAP04_IMP_PERVISTO DECIMAL(17,2) NULL,
  PRIMARY KEY (TAP05_COD_TIPOINGRESO)
);
-- -----------------------------------------------------
-- Table TIA_APP_INGRESOSMES
-- -----------------------------------------------------
DROP TABLE IF EXISTS TIA_APP_INGRESOSMES;
CREATE TABLE IF NOT EXISTS TIA_APP_INGRESOSMES (
  TAP06_COD_INGRESO VARCHAR(6) NOT NULL,
  TAP06_MES VARCHAR(3) NULL,
  TAP06_COD_TIPOINGRESO VARCHAR(3) NULL,
  TAP06_IMP DECIMAL(17,2) NULL,
  TAP06_OBSERVACIONES VARCHAR(45) NULL,
  PRIMARY KEY (TAP06_COD_INGRESO)
);
-- -----------------------------------------------------
-- Table TIA_APP_GASTOS
-- -----------------------------------------------------
DROP TABLE IF EXISTS TIA_APP_GASTOS;
CREATE TABLE IF NOT EXISTS TIA_APP_GASTOS (
  TAP02_COD_GASTO VARCHAR(6) NOT NULL,
  TAP02_COD_TIPOGASTO VARCHAR(3) NULL,
  TAP02_MES VARCHAR(3) NULL,
  TAP02_IMP_PERVISTO DECIMAL(17,2) NULL,
  PRIMARY KEY (TAP02_COD_GASTO)
);
-- -----------------------------------------------------
-- Table TIA_APP_GASTOMENSUAL
-- -----------------------------------------------------
DROP TABLE IF EXISTS TIA_APP_GASTOMENSUAL;
CREATE TABLE IF NOT EXISTS TIA_APP_GASTOMENSUAL (
  TAP03_COD_GASTO VARCHAR(6) NOT NULL,
  TAP03_IMP_COBRADO DECIMAL(17,2) NULL,
  TAP03_OBSERVACIOENS VARCHAR(100) NULL,
  PRIMARY KEY (TAP03_COD_GASTO)
);
