DROP TABLE IF EXISTS TIA_SEG_PERSONAS;
CREATE TABLE IF NOT EXISTS TIA_SEG_PERSONAS (
  TIA01_COD_PERSONA INT NOT NULL,
  TIA01_DIRELEC VARCHAR(200) NOT NULL,
  TIA01_NOMBRE VARCHAR(200) NULL,
  TIA01_APELLIDOS VARCHAR(200) NULL,
  TIA01_ULTIMO_ACCESS DATETIME NULL,
  TIA01_LOGIN_PASS VARCHAR(10) NULL,
  PRIMARY KEY (TIA01_COD_PERSONA, TIA01_DIRELEC)
 );
DROP TABLE IF EXISTS TIA_SEG_MESES;
CREATE TABLE IF NOT EXISTS TIA_SEG_MESES (
   TIA02_COD_MES VARCHAR(3) NOT NULL,
   TIA02_DESC_MES VARCHAR(10) NOT NULL,
   PRIMARY KEY (TIA02_COD_MES)
 );
 DROP TABLE IF EXISTS TIA_APP_TIPOGASTO;
 CREATE TABLE IF NOT EXISTS TIA_APP_TIPOGASTO (
   TAP01_COD_TIPOGASTO VARCHAR(3) NOT NULL,
   TAP01_DESC_GASTO VARCHAR(50) NOT NULL,
   TAP01_PRIOCIDAD INT NOT NULL, -- SI EL GASTO ES ANUAL=12, BI-ANUAL=2, ETC... 0=EXPORADICO,
   TAP01_FECHA_INICIO DATETIME NULL,
   TAP01_FECHA_FIN DATETIME NOT NULL,
   TAP01_IMP_PERVISTO DECIMAL(17,2) NOT NULL,
   PRIMARY KEY (TAP01_COD_TIPOGASTO)
 );
 DROP TABLE IF EXISTS TIA_APP_GASTOS;
 CREATE TABLE IF NOT EXISTS TIA_APP_GASTOS (
   TAP02_COD_GASTO VARCHAR(6) NOT NULL,
   TAP02_COD_TIPOGASTO VARCHAR(3) NULL,
   TAP02_MES VARCHAR(3) NULL,
   TAP02_IMP_COBRADO DECIMAL(17,2) NULL,
   TAP02_OBSERVACIOENS VARCHAR(100) NULL,
   PRIMARY KEY (TAP02_COD_GASTO)
 );
 DROP TABLE IF EXISTS TIA_APP_GASTOS_GRUPO;
 CREATE TABLE IF NOT EXISTS TIA_APP_GASTOS_GRUPO (
   TAP03_COD_GRUPO VARCHAR(6) NOT NULL,
   TAP03_COD_TIPOGASTO VARCHAR(3) NOT NULL,
   TAP03_NOMBRE_GRUPO VARCHAR(45) NULL,
   PRIMARY KEY (TAP03_COD_GRUPO, TAP03_COD_TIPOGASTO)
 );
 DROP TABLE IF EXISTS TIA_APP_INGRESOS;
 CREATE TABLE IF NOT EXISTS TIA_APP_INGRESOS (
   TAP04_COD_TIPOINGRESO VARCHAR(3) NOT NULL,
   TAP04_DEC_INGRESO VARCHAR(45) NULL,
   TAP04_PRIOCIDAD INT NULL, -- NUMERO DE MESES QUE SE COBRA ANULAMENTE.
   TAP04_IMP_PERVISTO DECIMAL(17,2) NULL,
   PRIMARY KEY (TAP04_COD_TIPOINGRESO)
 );
DROP TABLE IF EXISTS TIA_APP_INGRESOSMES;
 CREATE TABLE IF NOT EXISTS TIA_APP_INGRESOSMES (
   TAP05_COD_INGRESO VARCHAR(6) NOT NULL,
   TAP05_COD_TIPOINGRESO VARCHAR(3) NULL,
   TAP05_MES VARCHAR(3) NULL,
   TAP05_IMP DECIMAL(17,2) NULL,
   TAP05_OBSERVACIONES VARCHAR(45) NULL,
   PRIMARY KEY (TAP05_COD_INGRESO)
 );
INSERT INTO TIA_SEG_PERSONAS (TIA01_COD_PERSONA, TIA01_DIRELEC, TIA01_NOMBRE, TIA01_APELLIDOS, TIA01_ULTIMO_ACCESS, TIA01_LOGIN_PASS) VALUES(1,'tjoelsm@gmail.com','Tiago Joel', 'Da Silva Monteiro', CURRENT_DATE, 'tiago123');
INSERT INTO TIA_SEG_MESES (TIA02_COD_MES, TIA02_DESC_MES) VALUES('ENE', 'ENERO');
INSERT INTO TIA_SEG_MESES (TIA02_COD_MES, TIA02_DESC_MES) VALUES('FEB', 'FEBRERO');
INSERT INTO TIA_SEG_MESES (TIA02_COD_MES, TIA02_DESC_MES) VALUES('MAR', 'MARZO');
INSERT INTO TIA_SEG_MESES (TIA02_COD_MES, TIA02_DESC_MES) VALUES('ABR', 'ABRIL');
INSERT INTO TIA_SEG_MESES (TIA02_COD_MES, TIA02_DESC_MES) VALUES('MAY', 'MAYO');
INSERT INTO TIA_SEG_MESES (TIA02_COD_MES, TIA02_DESC_MES) VALUES('JUN', 'JUNIO');
INSERT INTO TIA_SEG_MESES (TIA02_COD_MES, TIA02_DESC_MES) VALUES('JUL', 'JULIO');
INSERT INTO TIA_SEG_MESES (TIA02_COD_MES, TIA02_DESC_MES) VALUES('AGO', 'AGOSTO');
INSERT INTO TIA_SEG_MESES (TIA02_COD_MES, TIA02_DESC_MES) VALUES('SEP', 'SEPTIEMBRE');
INSERT INTO TIA_SEG_MESES (TIA02_COD_MES, TIA02_DESC_MES) VALUES('OCT', 'OCTUBRE');
INSERT INTO TIA_SEG_MESES (TIA02_COD_MES, TIA02_DESC_MES) VALUES('NOV', 'NOVIEMBRE');
INSERT INTO TIA_SEG_MESES (TIA02_COD_MES, TIA02_DESC_MES) VALUES('DIC', 'DICIEMBRE');
INSERT INTO TIA_APP_TIPOGASTO (TAP01_COD_TIPOGASTO,TAP01_DESC_GASTO,TAP01_PRIOCIDAD,TAP01_FECHA_INICIO,TAP01_FECHA_FIN,TAP01_IMP_PERVISTO) VALUES('HES','Hipoteca España',12,'2016-07-01 00:00:00','2020-07-31 00:00:00', 181.27);
INSERT INTO TIA_APP_TIPOGASTO (TAP01_COD_TIPOGASTO,TAP01_DESC_GASTO,TAP01_PRIOCIDAD,TAP01_FECHA_INICIO,TAP01_FECHA_FIN,TAP01_IMP_PERVISTO) VALUES('HPT','Hipoteca Portugal',12,'2016-07-01 00:00:00','2020-07-31 00:00:00', 178.48);
INSERT INTO TIA_APP_TIPOGASTO (TAP01_COD_TIPOGASTO,TAP01_DESC_GASTO,TAP01_PRIOCIDAD,TAP01_FECHA_INICIO,TAP01_FECHA_FIN,TAP01_IMP_PERVISTO) VALUES('PRE','Prestatamos Personal',12,'2016-07-01 00:00:00','2020-07-31 00:00:00', 512.45);
INSERT INTO TIA_APP_GASTOS (TAP02_COD_GASTO, TAP02_COD_TIPOGASTO, TAP02_MES, TAP02_IMP_COBRADO, TAP02_OBSERVACIOENS) VALUES('HESENE','HES','ENE',170.32, 'hipoteca españa de enero');
INSERT INTO TIA_APP_GASTOS (TAP02_COD_GASTO, TAP02_COD_TIPOGASTO, TAP02_MES, TAP02_IMP_COBRADO, TAP02_OBSERVACIOENS) VALUES('HPTENE','HPT','ENE',169.21, 'hipoteca portugal de enero');
INSERT INTO TIA_APP_GASTOS_GRUPO (TAP03_COD_GRUPO, TAP03_COD_TIPOGASTO, TAP03_NOMBRE_GRUPO) VALUES('FIJOS','HES','Gastos Fijos - Hipoteca España');
INSERT INTO TIA_APP_GASTOS_GRUPO (TAP03_COD_GRUPO, TAP03_COD_TIPOGASTO, TAP03_NOMBRE_GRUPO) VALUES('FIJOS','HPT','Gastos Fijos - Hipoteca Portugal');
INSERT INTO TIA_APP_GASTOS_GRUPO (TAP03_COD_GRUPO, TAP03_COD_TIPOGASTO, TAP03_NOMBRE_GRUPO) VALUES('FIJOS','PRE','Gastos Fijos - Prestamos Personal');
INSERT INTO TIA_APP_INGRESOS (TAP04_COD_TIPOINGRESO, TAP04_DEC_INGRESO, TAP04_PRIOCIDAD, TAP04_IMP_PERVISTO) VALUES('NTI','Nomina Tiago',12,2000);
INSERT INTO TIA_APP_INGRESOS (TAP04_COD_TIPOINGRESO, TAP04_DEC_INGRESO, TAP04_PRIOCIDAD, TAP04_IMP_PERVISTO) VALUES('NAN','Nomina ANA',12,1000);
INSERT INTO TIA_APP_INGRESOS (TAP04_COD_TIPOINGRESO, TAP04_DEC_INGRESO, TAP04_PRIOCIDAD, TAP04_IMP_PERVISTO) VALUES('RPT','Alquilar Casa PT',12,320);
INSERT INTO TIA_APP_INGRESOSMES (TAP05_COD_INGRESO, TAP05_COD_TIPOINGRESO, TAP05_MES, TAP05_IMP, TAP05_OBSERVACIONES) VALUES('NTIENE','ENE','NTI',2100,'Nomina de Enero');